### ISSUE TITLE
Error: Fail to load dependabot/fetch-metadata/v1.3.2/action.yml

### ISSUE THREAD

**Issue by fredflev** [dependabot/fetch-metadata#234]
Hi, 

I am getting the following error when upgrading from `1.3.1 to 1.3.2`: 

```log
Download action repository 'dependabot/fetch-metadata@v1.3.2' (SHA:90ed90dba204fdf8970c1f891b4349c96353f220)
Error: dependabot/fetch-metadata/v1.3.2/action.yml:
Error: dependabot/fetch-metadata/v1.3.2/action.yml: (Line: 18, Col: 113, Idx: 682) - (Line: 18, Col: 141, Idx: 710): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load dependabot/fetch-metadata/v1.3.2/action.yml
```

There seems to be a syntax error in the `description` field:

```console
'true' vs `true`
```

https://github.com/dependabot/fetch-metadata/blob/90ed90dba204fdf8970c1f891b4349c96353f220/action.yml#L16-L19

**Comment by fredflev** [comment]
Closing this, just saw the fix at: https://github.com/dependabot/fetch-metadata/pull/232
